### ISSUE TITLE
Wrong coordinates when windows 10 scale is higher than 100%

### ISSUE THREAD

**Issue by devmondo** [nut-tree/nut.js#183] opened 2020-11-22 16:30 UTC
**Version**
1.5.0
**Short overview**
Awesome work there!
I have an issue with Wrong coordinates when windows 10 scale is higher than 100% and 4K resolution
There is no error, and the cursor moves fine in the code below. just to a wrong coordinates because of scaling.

when tested with 100% scale all is perfect.

![image](https://user-images.githubusercontent.com/1266367/99909324-43c2f700-2d01-11eb-94f8-aefb3db2d6ba.png)

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
No Error
**Steps to reproduce error**
```js
        screen.config.resourceDirectory = "./";
        screen.config.confidence = 0.5;
        const dim =await screen.find(path.resolve("./cat_americanwire.jpg"));
		await mouse.move(await straightTo(await centerOf(dim)));
```

**Comment by s1hofmann** [comment] 2020-11-23 00:09
Hi @devmondo 👋 

looks like you've discovered a bug here!
I'll try to reproduce the issue on one of my machines!

Best regards

Simon

**Comment by devmondo** [comment] 2020-11-23 08:31
@s1hofmann thanks a bunch :)

**Comment by ThomasR** [comment] 2020-11-29 11:38
This affects also screenshots: for example if your scale is set to 200%, then `libnut.screen.capture()` only captures the left top quadrant of the screen.

**Comment by ThomasR** [comment] 2020-11-29 11:55
https://github.com/nut-tree/libnut/blob/45529edf4a8f86ec39ae9eecf040578de375e9c2/src/win32/screen.c#L7-L8

I think using `SM_CXVIRTUALSCREEN` and `SM_CYVIRTUALSCREEN` here might fix that, but could cause other issues.

**Comment by s1hofmann** [comment] 2020-11-29 15:35
@ThomasR Thanks for the hint!

**Comment by s1hofmann** [comment] 2020-12-03 18:46
So, I did some testing on this problem and came to the following conclusion:

- Reading `SM_CXVIRTUALSCREEN` and `SM_CYVIRTUALSCREEN` does not work. It'll return the size of all virtual screens but with scaling applied, still returns the *wrong* resolution
- [GetDeviceCaps](https://docs.microsoft.com/en-gb/windows/win32/api/wingdi/nf-wingdi-getdevicecaps?redirectedfrom=MSDN) also returns resolution with scaling applied and therefor returns just a portion of the full screen

However, retrieving the actual bitmap from the desktop device context give the correct resolution, even with scaling applied.
Only thing left to verify is whether this behaviour still applies with multiple monitors.

**Comment by s1hofmann** [comment] 2021-04-05 20:59
Should be fixed with https://github.com/nut-tree/libnut/pull/59 and available in `@nut-tree/nut-js@next`

**Closed by s1hofmann** 2021-04-05 20:59 UTC
Labels: bug
