### ISSUE TITLE
cant find darwin/fials compile gyp

### ISSUE THREAD

**Issue by richmailYT** [nut-tree/nut.js#317] opened 2021-11-24 17:30 UTC
**Version**
lastest

**Short overview**
cant find darwin/fials compile gyp
**Issue occurs on**
- [x] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
https://pastebin.com/cMYYHTLm
**Steps to reproduce error**
`npx create-electron-app@latest my-app`
`cd my-app`
`npm install @hut-tree/nut-js`
`npm start`
error

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment] 2021-11-24 20:13
Hi @richmailYT 👋 

Which version of Electron on which plattform are you using?

**Comment by richmailYT** [comment] 2021-11-25 13:14
@s1hofmann using 12.2.3 becuase one of my dependencys needs that version. Now it shows up as `command not found` even though its listed as a dev dependency in package.json

**Comment by richmailYT** [comment] 2021-11-25 13:21
upgraded to 16.0.2 to see if anything would change: nope

**Comment by s1hofmann** [comment] 2021-11-25 13:45
nut.js provides prebuilds for Electron 12.x.x., `electron-rebuild` should take care of that.

Are you using an M1 Mac or an Intel one?

**Comment by richmailYT** [comment] 2021-11-25 13:47
@s1hofmann im on an intel. How do I use `electron-rebuild`?

**Comment by s1hofmann** [comment] 2021-11-25 13:57
Install it via `npm i electron-rebuild`, then add something like

```json
  "scripts": {
    "prestart": "electron-rebuild",
    "start": "electron ."
  },
```

to your `package.json`.

But just to make sure: I just did a double check following your mentions steps to reproduce.
The setup with Electron 12.2.3 and nut.js works out of the box?

**Comment by richmailYT** [comment] 2021-11-25 14:34
@s1hofmann it dosnt work. It throws 
```App threw an error during load
Error: The module '/Users/richmail/Document/autoclicker-electron/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/richmail/Document/autoclicker-electron/node_modules/opencv4nodejs-prebuilt/lib/cv.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)```
with electron 12.2.3 and node 14.18.1

**Comment by s1hofmann** [comment] 2021-11-25 14:35
Could you please create a repo and link it here so I can verify it myself?

**Comment by richmailYT** [comment] 2021-11-25 14:43
@s1hofmann https://github.com/richmailYT/AutoClicker/tree/main

**Comment by s1hofmann** [comment] 2021-11-25 14:58
It works like a charm with the exact steps I provided earlier.

`node v16.13.0`
`Electron v12.2.3`

Going to close this now, as I can't reproduce.

**Closed by s1hofmann** 2021-11-25 14:58 UTC

**Comment by richmailYT** [comment] 2021-11-25 15:42
I got ti to work. you add 
 ```
 "scripts": {
    "prestart": "electron-rebuild",
    "start": "electron ."
  },
```

to package.json after you have installed electron rebuild (delet package-lock.json and node moduals before  nd reinstall everything with npm install)
