### ISSUE TITLE
Some models report error problems under Windows 10

### ISSUE THREAD

**Issue by ByLiangCheng** [nut-tree/nut.js#495] opened 2023-03-29 06:29 UTC
**Version**
3.1.1
**Short overview**
The version of Windows 10 is Professional Edition

```
const { keyboard, Key } = require('@nut-tree/nut-js')
      const copyShortcut = [superKey, Key.C]
      await keyboard.pressKey(...copyShortcut)
      await keyboard.releaseKey(...copyShortcut)
```

At startup, some windows 10 systems will prompt this error in the figure, causing the application to fail to start

**Issue occurs on**

- [windows10 ] Dev/Host system

**Detailed error description**
![7adf3066614ae071c41d0d73bdca4c4](https://user-images.githubusercontent.com/45414993/228445296-b10e2e4b-3ee6-4032-85cf-61c341cbb967.png)

**Comment by s1hofmann** [comment] 2023-03-29 07:11
Hi @ByLiangCheng 👋 

Looks like you're running an Electron app?
This error might be related to your build process, do you have a repo to check out?

**Comment by s1hofmann** [comment] 2023-03-29 09:16
Well my guess is that the actual root cause is a missing C++ runtime on the target systems.

nut.js, or more specifically, it’s native bindings in use, do ship the required libs.
If your build process does not include these libs, your users will have to manually install the runtime redistributable.

**Comment by s1hofmann** [comment] 2023-03-30 17:14
@ByLiangCheng Do you have any update on this?

**Comment by ByLiangCheng** [comment] 2023-03-31 06:58
Hello, do you mean when you lack C ++ in the system?So how to add?Do users operate by themselves?Is there any way to not let the user's operation be solved

**Comment by ByLiangCheng** [comment] 2023-04-01 14:37
Understood, I will find time to test it later. Thank you.

**Comment by s1hofmann** [comment] 2023-04-12 21:47
@ByLiangCheng I'll close this for now, feel free to re-open on update

**Closed by s1hofmann** 2023-04-12 21:47 UTC
