### ISSUE TITLE
On Mac, the Electron program will always display a permission setting window every time it is opened.

### ISSUE THREAD

**Issue by mushan0x0** [nut-tree/nut.js#476] opened 2023-02-15 13:18 UTC
**Version**

3.0.0

**Short overview**

```ts
import { Key, keyboard } from "@nut-tree/nut-js";
keyboard.pressKey(Key.LeftControl);
```

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

Every time the official packaged Electron program is opened on a MacOS 13.0.1, a permission request window will pop up, even for those that have already been authorized. I hope that it can be manually triggered and that those who have already been authorized will not be prompted again.

**Comment by s1hofmann** [comment] 2023-02-15 14:21
The lowlevel provider of nut.js checks the required permissions during runtime. If they are not given, the permission request dialogue is shown.

So once the required permissions are given, the dialogue wont be shown.

**Comment by s1hofmann** [comment] 2023-02-15 20:21
I can't reproduce said issue.

I just double checked and did a clean build of an Electron application using nut.js.
Works exactly like I described above.

Closing, feel free to re-open with additional info like a repo I can use to test.

Best regards

Simon

**Closed by s1hofmann** 2023-02-15 20:21 UTC
Labels: Can't reproduce

**Comment by ahmedmukhtar1133** [comment] 2023-03-21 19:13
Facing exact same issue, it keep asking for permissions each time app opened.

**Comment by s1hofmann** [comment] 2023-03-21 19:18
@ahmedmukhtar1133 On which version of nut.js?

**Comment by ahmedmukhtar1133** [comment] 2023-03-21 19:20
@s1hofmann 
   "@nut-tree/nut-js": "^3.0.0"
   "electron": "^22.1.0"

**Comment by s1hofmann** [comment] 2023-03-21 19:21
@ahmedmukhtar1133 Please upgrade nut.js to latest, e.g. `3.1.1`

**Comment by ahmedmukhtar1133** [comment] 2023-03-22 13:06
@s1hofmann In latest version now it just don't show the permission pop-up but quietly opens the accessibility screen each time.
