### ISSUE TITLE
Can't use mouse.move function on win10

### ISSUE THREAD

**Issue by bluedarker** [nut-tree/nut.js#136] opened 2020-05-12 14:54 UTC
Hi @s1hofmann 
**Version**
@nut-tree/nut-js@1.4.1-next.20200507012528
Windows 10 version 1809(build 17763.1158)
Electron 8.2.3
Node 12.13.0
**Short overview**
Just simple code:`await mouse.move(right(500))` , it's not working on win10, but working on mac

Best regards

**Comment by s1hofmann** [comment] 2020-05-12 16:16
Hi @bluedarker,

I'm not able to reproduce this problem with my Windows setup.
Just to make sure: Are you running a "real" Windows machine, or a VM?

With VMs I can confirm that `nut.js` mouse movement will not actually move your cursor, although moving it to the right direction.
A simple test would be to do e.g. `await mouse.drag(straightTo(new Point(100, 100)))`; on the desktop, which should draw the selection rectangle.

**Comment by bluedarker** [comment] 2020-05-13 14:42
hi @s1hofmann ,
 I am using VM on Mac, and I have a test it runs smoothly on a "real " Windows.

many thanks again.

**Comment by s1hofmann** [comment] 2020-05-13 14:44
You're welcome!

**Closed by s1hofmann** 2020-05-13 14:44 UTC
