### ISSUE TITLE
Replacing the `uiohook-napi` library, supporting the monitoring of mouse and keyboard events

### ISSUE THREAD

**Issue by mushan0x0** [nut-tree/nut.js#527] opened 2023-09-02 06:29 UTC
**Short overview**

<img width="827" alt="image" src="https://github.com/nut-tree/nut.js/assets/29084441/d10d747e-6bc8-4023-80dd-85125a2e3285">

**Additional content**

The `uiohook-napi` library is good, but it has a problem of crashing and automatically exiting. It has been unresolved for several years and there are no better alternatives in the market. I think `nut.js` might be able to support all its functionalities.

**Comment by s1hofmann** [comment] 2023-09-05 10:17
Hi @mushan0x0 👋 

Since this is essentially a duplicate of #497, I'll close this issue.
Any progress made on input monitoring will be tracked on #497

**Closed by s1hofmann** 2023-09-05 10:17 UTC
Labels: duplicate
